### ISSUE TITLE
How to deal with connections that don't have types

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ux#25]
From https://github.com/atlasmap/atlasmap-ui/issues/60 we have some sample cases where the connections don't have types.  This could be a problem with the sample integrations, but then for HTTP connections there isn't a type is there?

In cases where the integration has a source or target that doesn't have a type of some kind to map, should the data mapper step not be available?  Otherwise I'd worry about the linked issue being a regular thing for folks...

**Comment by dongniwang** [comment]
Yeah, if we can know for sure there's no available type to map, we should not provide the data mapper step. 

Either not show the option or grayed out the option. 

cc: @sjcox-rh

**Comment by sjcox-rh** [comment]
Yup,  that makes sense. I just wouldn't show the option in this case.

**Comment by gashcrumb** [comment]
Cool, going to implement this as part of fixing the linked issue, thanks!
