### ISSUE TITLE
FTUE - Landing page design concept and workflow 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ux#30]

**Comment by sjcox-rh** [comment]
Latest Designs of FTUE once user first gets to iPaaS. This shows both paths that user can take from landing page.

Working on final visuals for landing page as well as the three animations. Will work with CSS dev from the UXD team to create landing page.

[iPaaS_FTUE_Designs.pdf](https://github.com/syndesisio/syndesis-ux/files/1249617/iPaaS_FTUE_Designs.pdf)
