### ISSUE TITLE
Change text in Create Connection pages to make it easier for user

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis-ux#36]
While we are all familiar with what a connector is, it is not so obvious to someone who is new to Syndesis. I think it would be good to avoid referring to connectors here to make user interactions more intuitive:

![image](https://user-images.githubusercontent.com/25067106/29876565-2ec5ce60-8d6b-11e7-8721-9b12c3f7b5d9.png)

Instead:
- Replace "Select Connector" with "Select Connection Type".
- Replace "Configure Connector" with "Configure Connection"

When the user clicks on the Salesforce connection type, the next page displays:
"Log into your Salesforce account to grant authorization for Syndesis to act on your behalf"
Please insert a period at the end of this complete sentence, and do likewise for selection of the Twitter connection type.

**Comment by dongniwang** [comment]
Personally, I'm fine with the changes. But wanted to hear what others think about this? @syndesisio/design-ux, any feedback?

Also, changing the language in this workflow would probably a review of how we're using the word **Connection** in other workflows and pages. 

For the period ones, are you talking about this screen?
![image](https://user-images.githubusercontent.com/24943812/29880955-3544e31e-8d77-11e7-9604-8ac1c92723ef.png)

**Comment by TovaCohen** [comment]
Yes, that's the screen I was referring to.

**Comment by sjcox-rh** [comment]
@TovaCohen, great suggestions, I'm fine with those changes as well. Less confusing for all involved is my personal opinion.

**Comment by gashcrumb** [comment]
Have raised this here https://github.com/syndesisio/syndesis-ui/issues/889, issues that require changes in the UI definitely need to get raised (or moved) in the UI repo, otherwise they'll never get done :-)

Closing this issue, we'll track the actual changes via syndesisio/syndesis-ui#889
