### ISSUE TITLE
Changes required for dynamic object/action form

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ux#4]
On the 'action' page, take out the 'configured fields' and for the ID it should be a dropdown or so, most likely will have at most 10 entries.

Potential additional issue to think about, for some actions like list or delete it should be possible to use a selector rather than a specific ID, so the action page for list/delete may be slightly different.

**Comment by gashcrumb** [comment]
Associated to https://github.com/syndesisio/syndesis-project/issues/14

**Comment by dongniwang** [comment]
Should SJ put the updated design in this issue thread then? Or put it back to to issue syndesisio/syndesis-project#14?

**Comment by gashcrumb** [comment]
Maybe short term let's just update syndesisio/syndesis-project#14 

But I feel like eventually these designs should go into this repo in some form like in the PDF, in which case  a PR that references the above issue containing the PDF would be good, as I fear having PDFs attached to issues will get either lost in the shuffle a bit, or duplicated and potentially cause confusion.

@rhuss WDYT?

**Comment by dongniwang** [comment]
I'm assuming I can upload attachments like PDFs/PNGs to a PR, right? 

Maybe only the final design gets to the main page https://syndesisio.github.io/syndesis-ux/.

**Comment by kahboom** [comment]
@dongniwang You can drag and drop PNGs to a PR but not PDFs. You can, however, link to one from a cloud server, for instance, if you have it saved to your Red Hat Google Drive account, you'd use the link to share it publicly.

**Comment by rhuss** [comment]
@dongniwang What about creating a PR which contains the PDF itself and which, when merged, would put the PDF in the proper directory in this repo ? I've seen you already created a PR, but just to recapitulate a bit:

* Create a fork of the GitHub repo syndesisio/syndesis-ux which then will be dongniwang/syndesis-ux. You can create the fork via the GitHub UI

![image](https://user-images.githubusercontent.com/99080/28060232-e07b5ba0-6626-11e7-8e32-44cad32adaff.png)

* Clone this fork to your local disk

```
git clone https://github.com/dongniwang/syndesis-ux
```

* Create a branch for the current work

```
cd syndesis-ux

# Create a local git branch
git co -b pr/004-dynamic-action-form

# Push the local branch to a remote branch of the same name
git push --set-upstream origin pr/004-dynamic-action-form
```

* Then in the directory `syndesis-ux` (maybe with the github issue id as prefix )

```
README.MD
design
+-- REAMDE.md    (containing the links to pdf stored in this dir +  a biref explanation
       004-dynamic-action-form.pdf
```

* When you finished an initial version, commit everything an push to your repo

```
# Commit your work
git commit -m "Initial design for Dynamic Action/Recovery #4" -a

# Push your changes to the branch on GitHub
git push
```

* On the GitHub UI create a PR

![image](https://user-images.githubusercontent.com/99080/28060981-3684f20c-6629-11e7-8c61-e467a32bf36e.png)


* .... and link this to the original issue

Then everyone can comment on the PR (not the issue) and see the PDF directly as part of the PR. Also, you can update the PR anytime but committing and pushing new versions of the PDFs.

When everyone agrees, the PR gets merged and will be placed in the right spot in the main repo.

BTW, how do you generate the web page https://syndesisio.github.io/syndesis-ux/ ? I can't see a `ghpage` branch, so I'm just wondering how it is created.

**Comment by dongniwang** [comment]
@kahboom @rhuss Thanks for the information! 

Let me try submitting a PR with the global settings page design (I'm working on the high-fidelity version).  Thank you for the step-by-step instruction, Roland! 

> BTW, how do you generate the web page https://syndesisio.github.io/syndesis-ux/ ? I can't see a ghpage branch, so I'm just wondering how it is created.

I just created it from the repo settings page. See below. 

1. On the syndesis-ux settings page,
![image](https://user-images.githubusercontent.com/24943812/28077077-ae78ca90-662e-11e7-99cd-be4f7c517559.png)

2. There's a section to create a GitHub page
![image](https://user-images.githubusercontent.com/24943812/28077116-cacc3678-662e-11e7-826f-0181b720e74a.png)

**Comment by rhuss** [comment]
Ok, understand. I was a bit confused because typically there is a dedicated branch for the web site. However it makes sense to stick to a single branch for this non-code repo.

**Comment by sjcox-rh** [comment]
Just a heads up, I created a pull request for this issue: https://github.com/syndesisio/syndesis-ux/pull/10

Let me know if I captured all of the changes discussed in the design, thanks!

@kahboom @gashcrumb @jimmidyson @dongniwang

**Comment by rhuss** [comment]
Closing the issue as the attached PRs has been merged.
