### ISSUE TITLE
Let's revisit the way we present action property values

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-ux#40]
In https://github.com/syndesisio/syndesis-ux/blob/master/designs/salesforceobjects/salesforceobjects.md#choose-object we assumed that we can generate a description for action properties (well one of action properties the object name). As it turns out we cannot get the description for a Salesforce object (even if the description is one of the fields associated with a Salesforce object).

Here we offer a table, and in the next screen for the unique id field we offer a drop down.

From the backends perspective we would need to have a `type` and a `description`. Type would drive how the data is displayed (table or dropdown), and description would be specified for table representation.

Perhaps we can simplify this, on the backend we have the technical value to be used and a label meant for human use.

**Comment by dongniwang** [comment]
cc: @sjcox-rh

**Comment by dongniwang** [comment]
How many items are we expect to see here? If not too many, I'm fine with just display a simple select - drop down for this. 

The concern about having a combo box (type ahead) is that I'm not sure if users know what they should be typing in here.

**Comment by gashcrumb** [comment]
I think the potential is for 100s of items, which kinda makes me think typeahead would be better.

**Comment by sjcox-rh** [comment]
Im okay with the combo box, input and drop-down. Would most users know what to type here? 100's of items could be overwhelming but I suppose it would provide some context in what they would need to input.

**Comment by dongniwang** [comment]
I think what we have on the basic filter page would be fine here. It's exactly a typeahead + dropdown.
