### ISSUE TITLE
JMS Connector: UX design 

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis-ux#52]
Notes from meeting with @kcbabo:

- UX design is needed for JMS (Java Messaging Service) connector and S3 connector
- JMS broker between producer and consumer; if we receive from JMS, we’re getting messages from the queue but we don’t know data type, so user must provide data type - via json example, json schema, xml example, xml schema, or other descriptor.
- Java objects (twitter); json data (salesforce); xml
- Use for JMS to/from another type of connector - will require configuration, upload schema or infer from sample data
- UX: when data types don’t match add a notification (“data types are not compatible”) - the corrective is to provide a transformation/mapping
- Example: JMS to Twitter (we know twitter expects java object; need step to define JMS data type)
-

**Comment by dongniwang** [comment]
Closing this issue and all typeless connection ux design will be found at https://github.com/syndesisio/syndesis-ux/issues/61
