### ISSUE TITLE
AWS S3 Connector: UX Design

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis-ux#56]
"Amazon S3 is a web service offered by Amazon Web Services. Amazon S3 provides storage through web services interfaces."

Product management @kcbabo - use cases for this connector? Similar to JMS connector I believe?

**Comment by amysueg** [comment]
@dhirajsb @kcbabo Would you be able to provide detailed use cases and requirements for this S3 connector? We understand that it is part of the class of "shapeless" connectors Epic. Need details to know what to include in screen mocks and interactions. Related to #52 - we do have a bit more information for the JMS connector. Thanks.

**Comment by kcbabo** [comment]
@amysueg  @oscerd is the developer working on the S3 connector.  AFAIK, there are no specific UX requirements for S3.  Existing designs for action selection and config will work just fine.

User story for typeless connections can be found here: https://github.com/syndesisio/syndesis-project/issues/182

**Comment by amysueg** [comment]
thanks @kcbabo  
@dongniwang enough to get started with?

**Comment by dongniwang** [comment]
@amysueg @kcbabo Thanks for the info. 

Closing this issue and all typeless connection ux design will be found at https://github.com/syndesisio/syndesis-ux/issues/61
