### ISSUE TITLE
Tech Extensions: ui users cannot edit name and description

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis-ux#58]
I've found there's still a place in the doc that states that the user is able to edit name and description of a tech extension. Third picture [here](https://github.com/syndesisio/syndesis-ux/blob/master/designs/technical_extensions/tech_ext.md) and comments below ("User can inline edit Name and Description.").

We missed it during review.

@lburgazzoli , @dongniwang

**Comment by nicolaferraro** [comment]
Also this [picture](https://github.com/syndesisio/syndesis-ux/blob/master/designs/technical_extensions/img/technical_extensions_details_delete.png) report a pencil beside name and description.

**Comment by dongniwang** [comment]
Thanks for catching these! @nicolaferraro Just put a [PR](https://github.com/syndesisio/syndesis-ux/pull/59) in for this, please review.
