### ISSUE TITLE
[UX Design] Global Settings Page 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ux#6]
As a **Citizen Developer**, I want to access and manage client ID and client secret. I expect to be able to:
- Register a new application/service
- Edit an existing application/service
- Delete (remove) an existing application/service 

Currently, we support one registration per connector (meaning a client ID and client secret pair). 

From @zregvart 
> A bit of background on terminology, registration means configuring Syndesis as an OAuth capable application with the OAuth resource provider (Twitter, Salesforce, Facebook, GitHub...) at that point a Client ID and a Client Secret is defined. Authorization is when the client gives access to its resources at the resource provider through OAuth flow. Registration is typically done out of band.

From @rhuss 
> a registration is required on this global settings page to connect the Syndesis installation with Twitter. Only then one or more Twitter connection can be created on top of this by doing the twitter specific Twitter OAuth workflow.

Reference: syndesisio/syndesis-project#13, syndesisio/syndesis-project#28

AC:
- Review by: @kcbabo @rhuss @chirino @kahboom @gashcrumb @sjcox-rh 
- Final deliverables include: High fidelity design mockup of the Global Settings Page.

**Comment by rhuss** [comment]
Fixed as the PR has been merged.
