### ISSUE TITLE
[UX Design] Integration Lifecycle Handling 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ux#9]

**Comment by sjcox-rh** [comment]
@rhuss @dongniwang @kahboom @jimmidyson @kcbabo @gashcrumb New PR submitted with designs for the integration summary page! I have a couple questions in the PR, would love feedback since it's the first iteration.

Thanks!
https://github.com/syndesisio/syndesis-ux/pull/14
